---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: z2m-lab
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  dependsOn:
    - name: mosquitto-lab
      namespace: home
    - name: csi-driver-nfs
      namespace: storage
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.29.2

    env:
      TZ: Europe/Helsinki
      ZIGBEE2MQTT_DATA: /data

    service:
      main:
        ports:
          http:
            port: 8082

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "z2m-lab.${MAIN_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: z2m-lab-config-v1
        mountPath: "/data"

    tolerations:
      - key: "master"
        operator: "Equal"
        value: "false"
        effect: "NoSchedule"
