apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app modbus2x-lab
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: mosquitto-lab
      namespace: home
    - name: csi-driver-nfs
      namespace: storage
  values:
    image:
      repository: vaizki/modbus2x
      tag: 75d196e
    env:
      TZ: "${TZ}"
      MODBUS_MQTT_BROKER: mosquitto-lab
      #MODBUS_MQTT_USERNAME:
      #MODBUS_MQTT_PASSWORD:
      MODBUS_MQTT_PUBLISH_INTERVAL: 1
      MODBUS_HA_EXPIRE_AFTER: 30
    service:
      main:
        ports:
          http:
            enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: modbus2x-lab-config-v1
        mountPath: "/app"

    tolerations:
      - key: "master"
        operator: "Equal"
        value: "false"
        effect: "NoSchedule"
