---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto-lab
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
  values:
    image:
      repository: public.ecr.aws/docker/library/eclipse-mosquitto
      tag: 2.0.15

    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${SVC_MQTT_ADDR}"
        externalTrafficPolicy: Local
        ipFamilyPolicy: "SingleStack"
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
    configMaps:
      config:
        enabled: false
        data:
          mosquitto.conf: |
            per_listener_settings false
            listener 1883
            allow_anonymous true
            persistence true
            persistence_location /data/mosquitto/
            autosave_interval 1800
            connection_messages true
            autosave_interval 60
            #password_file /data/mosquitto/mosquitto_pwd
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    persistence:
      data:
        enabled: true
        mountPath: /data
        existingClaim: mosquitto-lab-config-v1
      config:
        enabled: false
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf

    resources:
      requests:
        memory: 64M
      limits:
        memory: 64M
