---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-lab-config-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-client
