---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app alertmanager-telegram
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  test:
    enable: false
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    env:
      TELEGRAM_CHAT_ID: "${TELEGRAM_MY_CHATID}"
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
    global:
      nameOverride: *app
    image:
      repository: janwh/alertmanager-telegram
      tag: latest
    service:
      main:
        ports:
          http:
            port: 8080
    resources:
      requests:
        cpu: 20m
        memory: 100Mi
