apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:7AOY5sHGIBGizXVKL8oa13a//WcAvjMxr+aKSIVCRpzjZQX60b1n4A==,iv:1608DDPOXylpPi/4N+UeWSuf3LybnD/sov5sEo8ULGA=,tag:fjHcC++jVwJbvpykhqp19g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdXo3ZTZOT2s0UzRBTW11
            alBjQ21DRTBKSjRWdFhjdFFJRWYxRTBZdTEwCmN6d1ljc0ZJQTU1aG96V2FwMG9w
            RnJkby8xNWxKQnIycFdKalJuOStrd28KLS0tIGM0QjRsOFpUNmlaRGZPN2pUb3RM
            SEtKdVp3V2x4RnAzd3c2UUZWVzhGUHMKyTPV5vsn7KvCHEKw2+0ls+0rqC7agvsv
            JjG/C6wSY1ApS+Wk1xsDhsW+wKlWbiuIPUTtP03peExF0gDZmITWkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T12:07:46Z"
    mac: ENC[AES256_GCM,data:VXkYnoiVTae9mWfVQD52YtqTUufk+s3pZIRr66nEyA6abX6K5bqUCYSZY9gS/hf9McgnI1ThFz3JNDq3Kqo3RccbbOnhkEO7dA3kfb9YT4155/RCkmyw7pk2m0wr3xH431DwkbIWvakwjHLYkILKpFEwnIRAIaufW9U8aSuuRfs=,iv:kfLMH43J8sJCF0hiAu5lphvG4pO89izYFlOxHo/sG2k=,tag:eNPRDQ5vuVDYnOP4lpAY8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
