---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome-lab
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
  values:
    image:
      repository: esphome/esphome
      tag: 2023.2.4

    env:
      ESPHOME__INSTANCE_NAME: ESPHome-lab
      ESPHOME__PORT: &port 6052
      ESPHOME__APPLICATION_URL: &host-cluster "esph-lab.${MAIN_DOMAIN}"
      ESPHOME__LOG_LEVEL: info

    # App needs to run as root because of this: https://github.com/esphome/issues/issues/2752
    securityContext:
      runAsNonRoot: false
      readOnlyRootFilesystem: false
      privileged: true
      allowPrivilegeEscalation: true

    service:
      main:
        ports:
          http:
            port: 6052

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "esph-lab.${MAIN_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: esph-lab-config-v1

    tolerations:
      - key: "master"
        operator: "Equal"
        value: "false"
        effect: "NoSchedule"
