---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: vmnet-router-v4
  namespace: metallb-system
spec:
  holdTime: 1m30s
  myASN: 64512
  peerASN: 64512
  peerAddress: 10.0.30.1
  peerPort: 179
  # https://github.com/metallb/metallb/issues/1537
  ebgpMultiHop: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: traefik
  namespace: metallb-system
spec:
  addresses:
    - 10.0.30.251 - 10.0.30.253
  avoidBuggyIPs: true
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipv4
  namespace: metallb-system
spec:
  addresses:
    - 10.0.30.200-10.0.30.250
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-other
  namespace: metallb-system
spec:
  ipAddressPools:
    - traefik
    - ipv4
