---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      hass:
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-mgmt",
                "namespace": "system",
                "ips": ["10.0.40.19/24"]
              }]
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"
                      
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.12.5
            probes: &probes
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
          code:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.96.4
            env:
              TZ: Europe/Helsinki
            workingDir: /config
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
            probes: *probes

        

    service:
      app:
        controller: hass
        ports:
          http:
            port: 8123
      code:
        controller: hass
        ports:
          code:
            port: 8080

    ingress:
      app:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        hosts:
          - host: &host "hass-lab.${MAIN_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
      code:
        className: nginx
        hosts:
          - host: &code-host "hasscode-lab.${MAIN_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: code
                  port: code
        tls:
          - hosts:
              - *code-host


    persistence:
      config:
        existingClaim: hass-config-v4
        advancedMounts:
          hass:
            app:
              - path: /config
            code:
              - path: /config
