---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - helm-release.yaml
patchesStrategicMerge:
  - ./patches/addons.yaml
labels:
  - pairs:
      app.kubernetes.io/name: hass
      app.kubernetes.io/instance: hass
