---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-test
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 16.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m
  values:
    deployment:
      kind: Deployment
      replicas: 1
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: "traefik"
        metallb.universe.tf/loadBalancerIPs: 10.0.30.251
      externalTrafficPolicy: Local
    logs:
      general:
        format: json
        level: INFO
      access:
        enabled: false
        format: json
        filters:
          statuscodes: "404,401,300-302"
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
      - "--api.insecure=true"
      - "--serverstransport.insecureskipverify=true"
      #- "--providers.kubernetesingress.ingressclass=traefik-test"
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
      - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=duckdns"
      - "--providers.kubernetesingress.ingressendpoint.publishedService=networking/traefik-test"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowexternalnameservices=true"
    env:
      - name: DUCKDNS_TOKEN
        valueFrom:
          secretKeyRef:
            name: duckdns
            key: token
    persistence:
      enabled: true
      path: /certs
      size: 128Mi
    ports.websecure.tls:
      enabled: true
      certResolver: "letsencrypt"
      domains:
        - main: k3sdev.duckdns.org
          sans:
            - "*.k3sdev.duckdns.orgr"
    ports:
      traefik:
        expose: true
      websecure:
        tls:
          enabled: true
          options: "default"
      metrics:
        port: 8082
        expose: false
        exposedPort: 8082
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        #        sniStrict: true
        cipherSuites:
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
          - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
          - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
          - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
          - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
          - TLS_AES_256_GCM_SHA384
          - TLS_AES_128_GCM_SHA256
    pilot:
      enabled: false
      token: ""
    experimental:
      plugins:
        enabled: false
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - traefik
            topologyKey: kubernetes.io/hostname
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 1Gi
