apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-traefik
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 10.7.1
      sourceRef:
        kind: HelmRepository
        name: ingress-traefik
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    crds:
      enabled: true
