additionalArguments:
  - "--certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
  - "--certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=duckdns"
env:
  - name: DUCKDNS_TOKEN
    valueFrom:
      secretKeyRef:
        name: duckdns
        key: token
ingressRoute:
  dashboard:
    enabled: false
persistence:
  enabled: true
  path: /certs
  size: 128Mi
ports.websecure.tls:
  enabled: true
  certResolver: "letsencrypt"
  domains:
    - main: k3sdev.duckdns.org
      sans: '*.k3sdev.duckdns.org'
spec:
  # Request this permanent IP address for traefik with MetalLB.
  loadBalancerIP: 10.0.30.251

podSecurityContext:
  fsGroup: null # Temporary workaround for certificate file permissions
