apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: db
  name: mariadb-full-access
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
