---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    prometheus:
      scrapeAnnotations: false
      metricsPort: 7472
      serviceAccount: prometheus-prometheus
      namespace: monitoring
      serviceMonitor:
        enabled: false
      prometheusRule:
        enabled: false

    crds:
      enabled: true

    speaker:
      # frr contains configuration specific to the MetalLB FRR container,
      # for speaker running alongside FRR.
      frr:
        enabled: false
        image:
          repository: frrouting/frr
          tag: v8.4.1
          pullPolicy:
        metricsPort: 7473
        resources: {}
      tolerateMaster: true
      livenessProbe:
        enabled: false
      readinessProbe:
        enabled: false
