---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${SECRET_DUCKDNS_DOMAIN}
  namespace: cert-manager
spec:
  secretName: ${SECRET_DUCKDNS_DOMAIN}-tls
  issuerRef:
    name: cert-manager-webhook-duckdns-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
  commonName: "${SECRET_DUCKDNS_DOMAIN}"
  dnsNames:
  - "${SECRET_DUCKDNS_DOMAIN}"
  - "*.${SECRET_DUCKDNS_DOMAIN}"
