---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager-webhook-duckdns
      version: v1.4.0
      sourceRef:
        kind: HelmRepository
        name: joshua-charts
        namespace: flux-system
  values:
    replicaCount: 1
    duckdns:
      token: SECRET_DUCKDNS_TOKEN
    clusterIssuer:
      email: SECRET_DUCKDNS_EMAIL
      production:
        create: true
      staging:
        create: true
    logLevel: 2
    image:
      repository: joshuakraitberg/cert-manager-webhook-duckdns
      tag: 1.4.0
      pullPolicy: IfNotPresent
    certManager:
      serviceAccountName: cert-manager
    service:
      type: ClusterIP
      port: 443
