---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: multus
      version: 5.0.7
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
  #See https://github.com/angelnu/helm-charts/blob/main/charts/apps/multus/values.yaml
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.0.2-thick
    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.5.0
      paths:
        config: /etc/cni/net.d
        bin: /opt/cni/bin
        
    resources:
      requests:
        cpu: 5m
        memory: 64M
      limits:
        memory: 64M

    hostPaths:
      netns: /var/run/netns