---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app multus
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      multus:
        type: daemonset
        initContainers:
          cni-plugins:
            image:
              repository: ghcr.io/buroa/cni-plugins
              tag: 1.6.2
        containers:
          multus:
            image:
              repository: ghcr.io/k8snetworkplumbingwg/multus-cni
              tag: v4.1.4
            command:
              - /thin_entrypoint
            args:
              - --cleanup-config-on-exit=true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 32Mi
            securityContext:
              privileged: true
    defaultPodOptions:
      hostNetwork: true
    persistence:
      cni-net-d:
        type: hostPath
        hostPath: /var/lib/rancher/k3s/agent/etc/cni/net.d
        globalMounts:
          - path: /host/var/lib/rancher/k3s/agent/etc/cni/net.d
      cni-bin:
        type: hostPath
        hostPath: /var/lib/rancher/k3s/data/current/bin
        globalMounts:
          - path: /host/lib/rancher/k3s/data/current/bin
    serviceAccount:
      create: true
      name: *app