---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-webhook-duckdns-production
  namespace: cert-manager
spec:
  acme:
    email: "${SECRET_DUCKDNS_EMAIL}"
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: cert-manager-webhook-duckdns-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          config:
            apiTokenSecretRef:
              name: "{SECRET_DUCKDNS_TOKEN}"
              key: "{SECRET_DUCKDNS_TOKEN}"
          groupName: acme.${SECRET_DUCKDNS_DOMAIN}
          solverName: duckdns

