apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - namespace.yaml
  - duckdns-production.yaml
    #- letsencrypt-production.yaml
    #- letsencrypt-staging.yaml
