apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app nodered-lab
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/k8s-at-home/node-red
      tag: v3.0.2
    env:
      TZ: "${TZ}"
    service:
      main:
        ports:
          http:
            port: 1880
    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "nodered-lab.${MAIN_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: nodered-lab-config-v1
        mountPath: "/data"
    resources:
      requests:
        memory: 64M
      limits:
        memory: 1Gi
