apiVersion: v1
kind: ConfigMap
metadata:
  name: kam-base
  namespace: voice
data:
  kamailio-base.cfg: |
    ###!define WITH_DEBUG
    #!define WITH_MYSQL
    #!define WITH_AUTH
    #!define WITH_USRLOCDB

    #!define DMQ_PORT 5062
    #!define DMQ_LISTEN net1:5062
    #!define DMQ_SERVER_ADDRESS udp:net1:5062
    #!define DMQ_NOTIFICATION_ADDRESS sip:kdmqlab.oatel.net:5062

    ####### Defined Values #########
    # *** Value defines - IDs used later in config
    #!ifdef WITH_DEBUG
    #!define DBGLEVEL 3
    #!else
    #!define DBGLEVEL 2
    #!endif
    
    #!ifdef WITH_MYSQL
    # - database URL - used to connect to database server by modules such
    #       as: auth_db, acc, usrloc, a.s.o.
    #!define DBURL "mysql://${KAMAILIO_USER}:${KAMAILIO_PASSWORD}@mariadb.db.svc.cluster.local/kamailio"
    #!endif
    
    #!ifdef WITH_MULTIDOMAIN
    # - the value for 'use_domain' parameters
    #!define MULTIDOMAIN 1
    #!else
    #!define MULTIDOMAIN 0
    #!endif
    
    # - flags
    #   FLT_ - per transaction (message) flags
    #!define FLT_ACC 1
    #!define FLT_ACCMISSED 2
    #!define FLT_ACCFAILED 3
    #!define FLT_NATS 5
    #       FLB_ - per branch flags
    #!define FLB_NATB 6
    #!define FLB_NATSIPPING 7
    
    ####### Global Parameters #########
    
    debug=DBGLEVEL
    log_stderror=no
    memdbg=5
    memlog=5
    log_facility=LOG_LOCAL0
    log_prefix="{$mt $hdr(CSeq) $ci} "
    children=8
    # auto_aliases=no
    alias="kam.oatel.net"
    listen=eth0:5060 advertise '${SVC_KAM_PUB_ADDR}':5060 name "s0"
    listen=net1:5062
    tcp_connection_lifetime=3605
    tcp_max_connections=2048
    enable_sctp=no
    
    ####### Custom Parameters #########
    
    #!ifdef WITH_PSTN
    /* PSTN GW Routing
     *
     * - pstn.gw_ip: valid IP or hostname as string value, example:
     * pstn.gw_ip = "10.0.0.101" desc "My PSTN GW Address"
     *
     * - by default is empty to avoid misrouting */
    pstn.gw_ip = "" desc "PSTN GW Address"
    pstn.gw_port = "" desc "PSTN GW Port"
    #!endif
    
    ####### Modules Section ########
    
    /* set paths to location of modules */
    # mpath="/usr/lib/kamailio/modules/"
    
    

    #!ifdef WITH_MYSQL
    loadmodule "db_mysql.so"
    #!endif
    
    loadmodule "jsonrpcs.so"
    loadmodule "kex.so"
    loadmodule "corex.so"
    loadmodule "tm.so"
    loadmodule "tmx.so"
    loadmodule "sl.so"
    loadmodule "rr.so"
    loadmodule "pv.so"
    loadmodule "maxfwd.so"
    loadmodule "usrloc.so"
    loadmodule "registrar.so"
    loadmodule "textops.so"
    loadmodule "textopsx.so"
    loadmodule "siputils.so"
    loadmodule "xlog.so"
    loadmodule "sanity.so"
    loadmodule "ctl.so"
    loadmodule "cfg_rpc.so"
    loadmodule "acc.so"
    loadmodule "counters.so"
    

    #!ifdef WITH_AUTH
    loadmodule "auth.so"
    loadmodule "auth_db.so"
    #!endif
    
    #!ifdef WITH_MULTIDOMAIN
    loadmodule "domain.so"
    #!endif
    
    #!ifdef WITH_PRESENCE
    loadmodule "presence.so"
    loadmodule "presence_xml.so"
    #!endif
    
    #!ifdef WITH_NAT
    loadmodule "nathelper.so"
    #!ifdef WITH_RTPENGINE
    loadmodule "rtpengine.so"
    #!else
    loadmodule "rtpproxy.so"
    #!endif
    #!endif
    
    #!ifdef WITH_HTABLE
    loadmodule "htable.so"
    #!endif
    
    #!ifdef WITH_DEBUG
    loadmodule "debugger.so"
    #!endif
    
    loadmodule "dmq.so"
    loadmodule "dmq_usrloc.so"
    loadmodule "dialog.so"

    # ----------------- setting module-specific parameters ---------------
    
    # ----- dmq params -----
    modparam("dmq", "server_address", "sip:net1:5062")
    modparam("dmq", "notification_address", "sip:kdmqlab.oatel.net:5062")
    modparam("dmq", "multi_notify", 1)
    modparam("dmq", "num_workers", 4)
    modparam("dmq", "ping_interval", 15)
    modparam("dmq_usrloc", "enable", 1)
    modparam("dmq_usrloc", "replicate_socket_info", 2)

    # ----- sanity params -----
    modparam("sanity", "autodrop", 0)
    
    # ----- tm params -----
    # auto-discard branches from previous serial forking leg
    modparam("tm", "failure_reply_mode", 3)
    # default retransmission timeout: 30sec
    modparam("tm", "fr_timer", 30000)
    # default invite retransmission timeout after 1xx: 120sec
    modparam("tm", "fr_inv_timer", 120000)
    
    # ----- rr params -----
    # set next param to 1 to add value to ;lr param (helps with some UAs)
    modparam("rr", "enable_full_lr", 0)
    # do not append from tag to the RR (no need for this script)
    modparam("rr", "append_fromtag", 0)
    
    # ----- registrar params -----
    modparam("registrar", "method_filtering", 1)
    /* uncomment the next line to disable parallel forking via location */
    # modparam("registrar", "append_branches", 0)
    /* uncomment the next line not to allow more than 10 contacts per AOR */
    # modparam("registrar", "max_contacts", 10)
    /* max value for expires of registrations */
    modparam("registrar", "max_expires", 3600)
    /* set it to 1 to enable GRUU */
    modparam("registrar", "gruu_enabled", 0)
    /* set it to 0 to disable Path handling */
    modparam("registrar", "use_path", 1)
    /* save Path even if not listed in Supported header */
    modparam("registrar", "path_mode", 0)
    
    # ----- acc params -----
    /* what special events should be accounted ? */
    modparam("acc", "early_media", 0)
    modparam("acc", "report_ack", 0)
    modparam("acc", "report_cancels", 0)
    /* by default we do not adjust the direct of the sequential requests.
     * if you enable this parameter, be sure the enable "append_fromtag"
     * in "rr" module */
    modparam("acc", "detect_direction", 0)
    /* account triggers (flags) */
    modparam("acc", "log_flag", FLT_ACC)
    modparam("acc", "log_missed_flag", FLT_ACCMISSED)
    modparam("acc", "log_extra",
            "src_user=$fU;src_domain=$fd;src_ip=$si;"
            "dst_ouser=$tU;dst_user=$rU;dst_domain=$rd")
    modparam("acc", "failed_transaction_flag", FLT_ACCFAILED)
    /* enhanced DB accounting */
    #!ifdef WITH_ACCDB
    modparam("acc", "db_flag", FLT_ACC)
    modparam("acc", "db_missed_flag", FLT_ACCMISSED)
    modparam("acc", "db_url", DBURL)
    modparam("acc", "db_extra",
            "src_user=$fU;src_domain=$fd;src_ip=$si;"
            "dst_ouser=$tU;dst_user=$rU;dst_domain=$rd")
    #!endif
    
    # ----- usrloc params -----
    modparam("usrloc", "timer_interval", 60)
    modparam("usrloc", "timer_procs", 1)
    modparam("usrloc", "use_domain", MULTIDOMAIN)
    /* enable DB persistency for location entries */
    #!ifdef WITH_USRLOCDB
    modparam("usrloc", "db_url", DBURL)
    modparam("usrloc", "db_mode", 2)
    #!endif
    
    # ----- dialog params -----
    modparam("dialog", "enable_dmq", 1)

    # ----- auth_db params -----
    #!ifdef WITH_AUTH
    modparam("auth_db", "db_url", DBURL)
    modparam("auth_db", "calculate_ha1", yes)
    modparam("auth_db", "password_column", "password")
    modparam("auth_db", "load_credentials", "")
    modparam("auth_db", "use_domain", MULTIDOMAIN)
    
    # ----- permissions params -----
    #!ifdef WITH_IPAUTH
    modparam("permissions", "db_url", DBURL)
    modparam("permissions", "load_backends", 1)
    #!endif
    
    #!endif
    
    # ----- domain params -----
    #!ifdef WITH_MULTIDOMAIN
    modparam("domain", "db_url", DBURL)
    /* register callback to match myself condition with domains list */
    modparam("domain", "register_myself", 1)
    #!endif
    
    #!ifdef WITH_PRESENCE
    # ----- presence params -----
    modparam("presence", "db_url", DBURL)
    
    # ----- presence_xml params -----
    modparam("presence_xml", "db_url", DBURL)
    modparam("presence_xml", "force_active", 1)
    #!endif
    
    #!ifdef WITH_NAT
    #!ifdef WITH_RTPENGINE
    # ----- rtpengine params -----
    modparam("rtpengine", "rtpengine_sock", "udp:127.0.0.1:2223")
    #!else
    # ----- rtpproxy params -----
    modparam("rtpproxy", "rtpproxy_sock", "udp:127.0.0.1:7722")
    #!endif
    # ----- nathelper params -----
    modparam("nathelper", "natping_interval", 30)
    modparam("nathelper", "ping_nated_only", 1)
    modparam("nathelper", "sipping_bflag", FLB_NATSIPPING)
    modparam("nathelper", "sipping_from", "sip:pinger@kamailio.org")
    
    # params needed for NAT traversal in other modules
    modparam("nathelper|registrar", "received_avp", "$avp(RECEIVED)")
    modparam("usrloc", "nat_bflag", FLB_NATB)
    #!endif
    
    #!ifdef WITH_HTABLE
    # ----- htable params -----
    #!ifdef WITH_ANTIFLOOD
    /* ip ban htable with autoexpire after 5 minutes */
    modparam("htable", "htable", "ipban=>size=8;autoexpire=300;")
    #!endif
    #!endif
    
    #!ifdef WITH_DEBUG
    # ----- debugger params -----
    modparam("debugger", "cfgtrace", 1)
    modparam("debugger", "log_level_name", "exec")
    #!endif
