---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kamailio
  namespace: voice
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      kamailio:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/kamailio/kamailio
              tag: 5.8.5-xenial
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-kam",
                "namespace": "system"
              }]
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"
          topologySpreadConstraints:
            - maxSkew: 2
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: kamailio

    service:
      app:
        controller: kamailio
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${SVC_KAM_PUB_ADDR}"
        externalTrafficPolicy: Local
        ipFamilyPolicy: "SingleStack"
        ipFamilies:
          - IPv4
        ports:
          sip-udp:
            enabled: true
            port: 5060
            protocol: UDP
          sip-tcp:
            enabled: true
            port: 5060
            protocol: TCP


    persistence:
      config:
        enabled: true
        type: configMap
        name: kam-app-conf
        globalMounts:
          - path: /etc/kamailio/kamailio.cfg
            subPath: kamailio.cfg
      config-base:
        enabled: true
        type: configMap
        name: kam-base
        globalMounts:
          - path: /etc/kamailio/kamailio-base.cfg
            subPath: kamailio-base.cfg
