---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: local-range
  namespace: voice
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "br0",
      "mode": "bridge",
      "capabilities": {
            "ips": true
          },
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.40.0/24",
        "rangeStart": "10.0.40.30",
        "rangeEnd": "10.0.40.36"
      }
    }'