apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kamailio-mariadb-full-access
  namespace: db
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: mariadb-full-access
  apiGroup: rbac.authorization.k8s.io
