apiVersion: v1
kind: Secret
metadata:
    name: kamailio-secret
    namespace: voice
type: Opaque
stringData:
    location: ENC[AES256_GCM,data:+/RRToea6tXxMgtXtf08gFs74CDwmc1lK8KKsBesR9elvThaPX25oiEMt3zPR3p6H4aVJJxrYXUzXQYRGaSBwRDRtvNo/dHL,iv:me8DAutrVhrnCTMlITA+ZUaWdvRFh94AbUN5M6/JiKA=,tag:FVJ69ir0utszF8cVeJn7Jw==,type:str]
    users: ENC[AES256_GCM,data:mFDcnnztIan5N8FWltgOpslRLr2Zm7ixeTqCeAgxhmnRnZrY6mKw6gFkGoNkz48D3RXhVYZbwmTpw8v9V/nKF1tInT6W751vmSsO0ZN3dJNaOhwbTRl//cPhsGt6MJdJ7/olQ3Q+g3AWMvMZwuv8YDwnY9/Upl8hbONnS7VG70sX2U7RRjtD,iv:VDbj+72+KNPp8d+YqPUGonsLaVlE0wh/n9ehtbwZcY4=,tag:nEuH8Bw9yHE2SXRBsWSMow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXY2RGd2s1MzYzZkNCbzY0
            WVNhZHB6QXhLcTRiSjQ4eDJzTHJycTNwNVJVCndlaGFXYnhlUDcxeTc1WnFKKzA0
            KzI2TW0zM2cwbFBtN29BQWVReXFYMXcKLS0tIGk5SkxaY1k1RU05aXhkVVNseXVu
            Tmh3cWtuVHozMi9MMFFQSkhVSkgzMDQKiNqt50fuaGmGq2YYMQcYlvRkFUNgiUYp
            gDA6DkVLd4WyZQfxKDwj+49hm+QAJozm+APZ990hhcxccJ2IqFrjng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T15:12:09Z"
    mac: ENC[AES256_GCM,data:YoYbzlQwB0TUDaTh71c4CNfjjeGwdezlVhxKrjmGkGmccPw770xGcUMZlM3G6b347cAkgF6s/1H/pJclntH0j7joorepLBxhQpkZ+cpXYOYlXziB9d6LbxIfTS0UiiSdZuEFJNwZgIbRlhVXL5Q35dFKoQd1fdeEOIax+eVesvM=,iv:v5GpawNqDTNM3Cl3JUx3rXSV1vjbYMdPUnCaBXuEoYY=,tag:BE/rCAp+4u9I2rjPLxS0xA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
